### PR TITLE
Barlow twins

### PR DESCRIPTION
**Pull request by KeremTurgutlu**
- Adding [Barlow Twins](https://arxiv.org/pdf/2103.03230.pdf) to vision module.
- Minor changes in docs, utility function arguments for mlp module creation.
- Removed GaussianBlur code, now it's available with kornia v0.5
- Finalized Barlow Twins Imagewang experiments.

### CODE REVIEW

**Comment by KeremTurgutlu** [comment]
Results on downstream iwang task is not as good as SwAV or MoCo.

**Comment by KeremTurgutlu** [comment]
@kai-tub let me know what you think

**Comment by kai-tub** [comment]
Thanks for asking for my opinion. :D
I haven't read the paper yet, so I just skimmed through the code, but all in all it looks good to me :)
But what happened to the Review-Notebook App?
I liked to be able to see the diffs of the jupyter notebooks directly.

**Comment by KeremTurgutlu** [comment]
@kai-tub I think I accidentally deleted that commit.

**Pull request merged**
